name: 1Zomboid-Essentials
version: 1.0
main: me.zeus.ZomboidEssentials.Core.ZomboidEssentials
description: Zomboid Essentials
commands:
  gamemode:
    description: Switch gamemodes
    syntax: /gamemode <mode>
  killall:
    description: Remove all entities in world
    syntax: /killall
  setspawn:
    description: Set spawn at current lcoation
    syntax: /setspawn
  setwarp:
    description: Set warp to current location
    syntax: /setwarp <name>
  spawn:
    description: Teleports you to spawn
    syntax: /spawn
  teleport:
    description: Teleports you to specified user
    syntax: /teleport <user>
  time:
    description: Sets time to specified
    syntax: /time <time-in-ticks>
  warp:
    description: Warps you to (or lists) warps
    syntax: /warp [name]